### ISSUE TITLE
Not able to make it works with Sensu 0.26.5

### ISSUE THREAD

**Issue by goldyfruit** [bimlendu/sensu-cachethq#5]
Hi guys,

Could you please confirm than this handler still working with Sensu 0.26.5 ?
I'm not able to make it works, I have almost the same behavior than #4 

```
$ cat test.json | /opt/sensu/embedded/bin/ruby --debug /opt/sensu/embedded/bin/cachethq.rb
Exception `LoadError' at /opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems.rb:1345 - cannot load such file -- rubygems/defaults/operating_system
Exception `LoadError' at /opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems.rb:1354 - cannot load such file -- rubygems/defaults/ruby
Exception `LoadError' at /opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55 - cannot load such file -- did_you_mean
Exception `LoadError' at /opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55 - cannot load such file -- sensu-handler
Using Ext extension for JSON.
/opt/sensu/embedded/bin/cachethq.rb:72: warning: method redefined; discarding old api_url
/opt/sensu/embedded/bin/cachethq.rb:28: warning: previous definition of api_url was here
/opt/sensu/embedded/bin/cachethq.rb:76: warning: method redefined; discarding old api_token
/opt/sensu/embedded/bin/cachethq.rb:32: warning: previous definition of api_token was here
warning: event filtering in sensu-plugin is deprecated, see http://bit.ly/sensu-plugin
/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugin-1.4.4/lib/sensu-handler.rb:112: warning: instance variable @api_settings not initialized
Exception `Errno::ENOENT' at /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugin-1.4.4/lib/sensu-plugin/utils.rb:18 - No such file or directory @ rb_sysopen - /etc/sensu/config.json
warning: occurrence filtering in sensu-plugin is deprecated, see http://bit.ly/sensu-plugin
Exception `Net::HTTPServerException' at /opt/sensu/embedded/lib/ruby/2.3.0/net/http/response.rb:120 - 400 "Bad Request"
Exception occured : 400 "Bad Request"
/opt/sensu/embedded/lib/ruby/2.3.0/net/http/response.rb:120:in `error!'
/opt/sensu/embedded/bin/cachethq.rb:64:in `verify_response'
/opt/sensu/embedded/bin/cachethq.rb:137:in `update_cachet'
/opt/sensu/embedded/bin/cachethq.rb:143:in `handle'
/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugin-1.4.4/lib/sensu-handler.rb:81:in `block in <class:Handler>'
```

Thanks for your help.

**Comment by jothoma1** [comment]
Hi,
any news on this ? i would like to test cachethq :)
